# name: myapp
# description: "A new Flutter project."

# dependencies:
#   flutter:
#     sdk: flutter
#   sqflite: ^2.0.0+4
#   path_provider: ^2.0.11
#   cupertino_icons: ^1.0.6
# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^3.0.0
# flutter:
#   uses-material-design: true
name: task_manager
description: A simple task tracking mobile application built with Flutter.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.3
  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
